name: Deploy Go Web API to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t pardes29/koistory-api:v1 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push pardes29/koistory-api:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to VPS and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Pull the latest image from Docker Hub
            if docker pull pardes29/koistory-api:v1; then
                echo "Image pulled successfully."
            else
                echo "Failed to pull image."
                exit 1
            fi

            # Change to the directory containing docker-compose.yaml
            cd /home/koi-story

            # Stop and remove existing containers if they are running
            docker compose down

            # Start the services using Docker Compose (in detached mode)
            docker compose up -d

            # Optional: Remove unused images to free up space
            dangling_images=$(docker images pardes29/koistory-api --filter "dangling=true" -q)
            if [ ! -z "$dangling_images" ]; then
                docker rmi $dangling_images
            fi
